# api call for signup
###
POST http://127.0.0.1:8000/register/
Content-Type: application/json

{
    "username":"user5",
    "password":"user123",
    "email":"user@gmail.com"
}


# api call for create employee
###
POST http://127.0.0.1:8000/employee/
Content-Type: application/json
Authorization:Basic user5:user123

{
    "name": "James Wilson",
    "department": "Finance",
    "designation": "Financial Analyst",
    "salary": 80000,
    "email": "j.wilson@company.com",
    "date_of_joining": "2023-05-22"
  }


# api call for list employees
###
GET http://127.0.0.1:8000/employee/
Accept: application/json
Authorization: Basic user3:user123



# api call for get specific employee
###
GET http://127.0.0.1:8000/employee/2/
Accept: application/json
Authorization: Basic user3:user123



# api call for update employee
###
PUT http://127.0.0.1:8000/employee/4/
Content-Type: application/json
Authorization: Basic user3:user123

{
  "name": "David Rodriguez Jose",
  "department": "Engineering",
  "designation": "Cloud Engineer",
  "salary": 105000,
  "email": "david.r@company.com",
  "date_of_joining": "2023-06-20"
}




# api call for delete employee
###
DELETE http://127.0.0.1:8000/employee/4/
Authorization: Basic user3:user123